name: Periodic health check

on:
  schedule:
    - cron: '0 18 * * *'
jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check Deployed service status
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://full-stack-open-pokedex-mmf.herokuapp.com
          follow-redirect: no
          max-attempts: 5
          retry-delay: 5s
  