name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:    
    branches: [main]    
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:    
    runs-on: ubuntu-18.04    
    steps:      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test 
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy to heroku
        if: ${{ github.event_name == 'push' && !contains( join( toJson(github.event.commits.*.message )), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.8.8
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phonebook-app-part-11"
          heroku_email: "mandy@fonoma.com"
          healthcheck: "https://phonebook-app-part-11.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2  #I didn't get the error but added this anyway
        if: ${{ github.event_name == 'push' && !contains( join( toJson(github.event.commits.*.message )), '#skip') }}
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains( join( toJson(github.event.commits.*.message )), '#skip') }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      #- name: Notification success
      #  if: ${{ github.event_name == 'push' && !contains( join( toJson(github.event.commits.*.message )), '#skip') && success() }}
      #  uses: 8398a7/action-slack@v3
      #  with:
      #    status: ${{ job.status }}
      #    fields: repo,message # selectable (default: repo,message)
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      - name: Notification fail
        if: ${{ github.event_name == 'push' && !contains( join( toJson(github.event.commits.*.message )), '#skip') && failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      - name: Notification success nice format
        if: ${{ github.event_name == 'push' && !contains( join( toJson(github.event.commits.*.message )), '#skip') && success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: job,commit,author,took
          custom_payload: |
            {
              username: 'action-slack',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `a new version deployed to https://phonebook-app-part-11.herokuapp.com/ (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}